proyecto/adopcion/urls.py
from django.urls import path
from .views import AdopcionListView, AdopcionDetailView, AdopcionFormView, AdopcionUpdateView, AdopcionDeleteView

urlpatterns = [
    
    path('adopcion', AdopcionListView.as_view(), name='adopcion'),
    path('adopcion/<int:pk>', AdopcionDetailView.as_view(), name='adopcion-detail'),
    path('adopcion/agregar-animal', AdopcionFormView.as_view(), name='agregar-animal'),
    path('adopcion/<int:pk>/editar/', AdopcionUpdateView.as_view(), name='editar-animal'),
    path('adopcion/<int:pk>/eliminar/', AdopcionDeleteView.as_view(), name='eliminar-animal'),

]

proyecto/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('blog', views.BlogListView.as_view(), name='blog'),
    path('blog/detail/<pk>/<title>', views.BlogDetailView.as_view(), name='blog_detail'),

]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from proyecto import settings
from django.conf.urls.static import static
from core.sitemaps import StaticSitemap, DynamicSitemap
from django.contrib.sitemaps.views import sitemap


# Sitemap

sitemaps = {'static' : StaticSitemap, 'dynamic' : DynamicSitemap}


# Django admin custom titles

admin.site.site_header = "Administración de Almanimal"
admin.site.site_title = "Administración de Almanimal"
admin.site.index_title = "Bienvenido a Administración de Almanimal"


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('administracion/', admin.site.urls),


    # Core app urls
    path('', include('adopcion.urls')),

    # Adopcion app urls
    path('', include('core.urls')),

    # Blog app urls
    path('', include('blog.urls')),

    # Usuarios app
    path('', include('usuario.urls')),

    # Allauth
    path('accounts/', include('allauth.urls')),

    path('sitemap.xml', sitemap, {'sitemaps' : sitemaps}, name="django.contrib.sitemaps.views.sitemap"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/adopcion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from django.templatetags.static import static
from core.image_compress import compress

# Create your models here.


class Animal(models.Model):

    class Sexo(models.TextChoices):
        MACHO = 'Macho'
        HEMBRA = 'Hembra'
        INDEFINIDO = 'Indefinido'


    class Tamaño(models.TextChoices):
        CHICO = 'Chico'      
        MEDIANO = 'Mediano'
        GRANDE = 'Grande'

    class TipoAnimal(models.TextChoices):
        PERRO = 'Perro'
        GATO = 'Gato'
        OTRO = 'Otro'

    class Tiempo(models.TextChoices):
        DIAS = 'Dias'
        SEMANAS = 'Semanas'
        MESES = 'Meses'
        AÑOS = 'Años'

    class RazaGato(models.TextChoices):
        MESTIZO = 'Mestizo'
        AMERICANO_DE_PELO_CORTO = 'Americano De Pelo Corto'
        ANGORA_TURCO = 'Angora Turco'
        AZUL_RUSO = 'Azul Ruso'
        BENGALI = 'Bengali'
        BOMBAY = 'Bombay'
        BRITISH_SHORTHAIR = 'British Shorthair'
        EUROPEO_DE_PELO_CORTO = 'Europeo De Pelo Corto'
        PERSA = 'Persa'
        SAGRADO_DE_BIRMANIA = 'Sagrado De Birmania'
        SIAMES = 'Siames'
        SNOWSHOE = 'Snowshoe'

    class RazaPerro(models.TextChoices):
        MESTIZO = 'Mestizo'
        AKITA_INU = 'Akita Inu'
        BASSET_HOUND_O_BATATA = 'Basset Hound O Batata'
        BEAGLE = 'Beagle'
        BICHON_FRISE = 'Bichon Frise'
        BORDER_COLLIE = 'Border Collie'
        BOXER = 'Boxer'
        BRACO_ALEMAN_KURZHAAR = 'Braco Aleman Kurzhaar'
        BRACO_HUNGARO_O_VIZSLA = 'Braco hungaro O Vizsla'
        BRETON = 'Breton'
        BULL_TERRIER = 'Bull Terrier'
        BULLDOG_FRANCES = 'Bulldog Frances'
        BULLDOG_INGLES = 'Bulldog Ingles'
        CANICHE = 'Caniche'
        CHIHUAHUA = 'Chihuahua'
        CHOW_CHOW = 'Chow Chow'
        COCKER_SPANIEL = 'Cocker Spaniel'
        COLLIE = 'Collie'
        DACHSHUND_O_SALCHICHA = 'Dachshund O Salchicha'
        DALMATA = 'Dalmata'
        DOBERMAN = 'Doberman'
        DOGO_ARGENTINO = 'Dogo Argentino'
        DOGO_DE_BURDEOS = 'Dogo de Burdeos'
        FOX_TERRIER = 'Fox Terrier'
        GALGO = 'Galgo'
        GOLDEN_RETRIEVER = 'Golden Retriever'
        GRAN_DANES = 'Gran Danes'
        JACK_RUSSELL_TERRIER = 'Jack Russell Terrier'
        LABRADOR_RETRIEVER = 'Labrador Retriever'
        LHASA_APSO = 'Lhasa Apso'
        MALTES = 'Maltes'
        MASTIN_NAPOLITANO = 'Mastin Napolitano'
        OVEJERO_ALEMAN = 'Ovejero Aleman'
        PASTOR_BELGA = 'Pastor Belga'
        PASTOR_INGLES = 'Pastor Ingles'
        PEKINES = 'Pekines'
        PILA = 'Pila'
        PINSCHER = 'Pinscher'
        PITBULL = 'Pitbull'
        POINTER = 'Pointer'
        PRESA_CANARIO = 'Presa Canario'
        PUG = 'Pug'
        ROTTWEILER = 'Rottweiler'
        SAMOYEDO = 'Samoyedo'
        SAN_BERNARDO = 'San Bernardo'
        SCHNAUZER = 'Schnauzer'
        SETTER_IRLANDES = 'Setter Irlandes'
        SHAR_PEI = 'Shar Pei'
        SHIBA_INU = 'Shiba Inu'
        SHIH_TZUHUSKY_SIBERIANO = 'Shih TzuHusky Siberiano'
        WEIMARANER = 'Weimaraner'
        WHIPPET = 'Whippet'
        YORKSHIRE_TERRIER = 'Yorkshire Terrier'


    class Meta:
        verbose_name = 'Animal'
        verbose_name_plural = 'Animales'


    def __str__(self):
        return self.nombre

    dueño = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Creador', limit_choices_to={'is_staff':True})
    nombre = models.CharField(verbose_name='Nombre', max_length=30, null=False, blank=False)
    tipo_animal = models.CharField(verbose_name='Tipo de animal', max_length=40, choices=TipoAnimal.choices, null=False, blank=False)
    raza_perro = models.CharField(verbose_name='Raza Perro', help_text='Dejar en blanco si es Gato u Otro', max_length=255, choices=RazaPerro.choices, null=True, blank=True)
    raza_gato = models.CharField(verbose_name='Raza Gato', help_text='Dejar en blanco si es Perro u Otro', max_length=255, choices=RazaGato.choices, null=True, blank=True)
    tamaño = models.CharField(verbose_name='Tamaño', max_length=40, choices=Tamaño.choices, null=False, blank=False)
    foto1 = models.ImageField(verbose_name="Foto 1", blank=True, null=True, upload_to='foto1')
    foto2 = models.ImageField(verbose_name="Foto 2", blank=True, null=True, upload_to='foto2')
    edad = models.IntegerField(verbose_name='Edad', null=False, blank=False)
    tiempo = models.CharField("Tiempo", max_length=20, choices=Tiempo.choices, null=False, blank=False)
    sexo = models.CharField(verbose_name='Sexo', max_length=20, choices=Sexo.choices, null=False, blank=False)
    descripcion = models.TextField(verbose_name='Descripcion', null=False, blank=False)
    caracter = models.TextField(verbose_name='Carácter', null=True, blank=True)
    vacunado = models.BooleanField(verbose_name='Vacunado', null=False, blank=False)
    desparasitado = models.BooleanField(verbose_name='Desparasitado', null=False, blank=False)
    castrado = models.BooleanField(verbose_name='Castrado', null=False, blank=False)
    comentario = models.TextField(verbose_name='Comentarios', null=True, blank=True)
    telefono = models.CharField("Teléfono de contacto", max_length=20)
    email = models.EmailField("Email de contacto", max_length=50)
    publicado = models.BooleanField(verbose_name='Publicado', default=False)
    creado = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    actualizado = models.DateTimeField(auto_now=True,verbose_name='Ultima actualización')

    
    def image_tag(self):
        if self.foto1 and hasattr(self.foto1, 'url'):
            return mark_safe(f'<img style="object-fit:cover; height:100px; width:100px" src={self.foto1.url} />')
        else:
            return mark_safe(f'<img style="object-fit:cover; height:100px; width:100px" src={static("/adopcion/img/no-image.png")} />')
    
    image_tag.short_description = ''


    def image_tag2(self):
        if self.foto2 and hasattr(self.foto2, 'url'):
            return mark_safe(f'<img style="object-fit:cover; height:100px; width:100px" src={self.foto2.url} />')
        else:
            return mark_safe(f'<img style="object-fit:cover; height:100px; width:100px" src={static("/adopcion/img/no-image.png")} />')
    
    image_tag2.short_description = ''


    def save(self, *args, **kwargs):
        # Borrando imagen anterior cuando es actualizada
        try:
            this = Animal.objects.get(id=self.id)
            if this.foto1 != self.foto1:
                this.foto1.delete()
            if this.foto2 != self.foto2:
                this.foto2.delete()
        except:
            pass

        # Chequeando si el usuario es staff para determinar si publicado debe ser True o False
        if self.dueño.is_staff:
            self.publicado = True

        # Comprimiendo imagenes
        if self.foto1:
            if self.foto1.size > 1000000:
                self.foto1 = compress(self.foto1)
        
        if self.foto2:
            if self.foto2.size > 1000000:
                self.foto2 = compress(self.foto2)

        # Chequeando el tipo de animal para dejar en nulo los camplos innecesarios
        if str(self.tipo_animal) == 'Perro':
            self.raza_gato = None
        elif str(self.tipo_animal) == 'Gato':
            self.raza_perro = None
        else:
            self.raza_perro = None
            self.raza_gato = None


        super(Animal, self).save(*args, **kwargs)


proyecto/adopcion/views.py
from django.shortcuts import render, redirect, HttpResponse


from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import Animal
from core.models import PaginaAdopcion

from .forms import AnimalForm

from django.contrib.auth.models import User

# Create your views here.



class AdopcionListView(ListView):
    
    model = Animal
    template_name = 'adopcion/adopcion_list.html'
    queryset = Animal.objects.all().order_by('-id').filter(publicado=True)
    paginate_by = 9

    def get_context_data(self, **kwargs):
        queries = super(AdopcionListView, self).get_context_data(**kwargs)
        queries['seo_description'] = PaginaAdopcion.objects.get(id=1).seo_description
        queries['head_image'] = PaginaAdopcion.objects.get(id=1).head_image
        return queries

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            if query == "mis_publicaciones":
                object_list = self.model.objects.filter(dueño__id=self.request.user.id).order_by('-id')
            else:
                object_list = self.model.objects.filter(tipo_animal=query, publicado=True).order_by('-id')
        elif query == None or query == "":
            object_list = self.model.objects.all().order_by('-id').filter(publicado=True)
        else:
            object_list = self.model.objects.none()
        return object_list 


class AdopcionDetailView(DetailView):

    model = Animal
    template_name = 'adopcion/adopcion_detail.html'

class AdopcionFormView(CreateView):

    template_name = 'adopcion/adopcion_form.html'
    form_class = AnimalForm

    def post(self, request):
        
        if request.method == 'POST':

            form = AnimalForm(request.POST, request.FILES)

            if form.is_valid():

                a = form.save(commit=False)
                a.dueño = User.objects.get(id=request.user.id)
                a.save()
                return redirect('adopcion')
            
            else:
                return HttpResponse('<h1>Hubo un error publicando el animal. Intentá nuevamente más tarde.</h1> <br> <a href="/">Volver al inicio.</a>')

class AdopcionUpdateView(UpdateView):

    model = Animal
    form_class = AnimalForm
    template_name = 'adopcion/adopcion_edit.html'
    success_url = '/adopcion/'


class AdopcionDeleteView(DeleteView):

    model = Animal
    success_url = '/adopcion/'

proyecto/adopcion/templates/adopcion/adopcion_edit.html
{% extends "core/base.html" %}


{% block title %} En adopcion {% endblock title %}

{% block image %} {% load static %} {% static 'core/img/adopcion-bg.jpg'%} {% endblock image %}

{% block cabecera %}
<h1> Adoptá</h1>
<p> Encontrá tu compañía ideal</p>
{% if request.user.is_authenticated %}
  <div class="mt-5 w-50 mx-auto">
    <a href="{% url 'agregar-animal' %}" class="btn btn-primary">Publicá un animal</a>
    <br><br>
  </div>
{% endif %}
{% endblock cabecera %}

{% block contenido %}

    <a href="{% url 'adopcion' %}">&larr; Volver</a>
    <br><br>

    {% if request.user.id == animal.dueño.id %}

    <div class="col-12">

        <form action="{% url 'editar-animal' animal.pk %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="card-deck">
              <div class="card">
                  <h5 class="card-header">Detalles</h5>
                  <div class="card-body">
                      <label for="id_nombre">Nombre:</label>
                      {{ form.nombre }}
                      <br>
                      <label for="id_tipo_animal">Tipo de animal:</label>
                      {{ form.tipo_animal }}
                      <br>
                      <div id="perro">
                        <label for="id_raza_perro">Raza:</label>
                        {{ form.raza_perro }}
                        <br>
                      </div>
                      <div id="gato">
                        <label for="id_raza_gato">Raza:</label>
                        {{ form.raza_gato }}
                        <br>
                      </div>
                      <label for="id_sexo">Sexo:</label>
                      {{ form.sexo }}
                      <br>
                      <label for="id_tamaño">Tamaño:</label>
                      {{ form.tamaño }}
                      <br>
                      <label for="id_edad">Edad:</label>
                      {{ form.edad }}
                      <br>
                      <label for="id_tiempo">Tiempo:</label>
                      {{ form.tiempo }}
                      <br>
                      <label for="id_caracter">Caracter:</label>
                      {{ form.caracter }}
                      <br>
                      <label for="id_descripcion">Descripción:</label>
                      {{ form.descripcion }}
                  </div>
              </div>

          </div>

          <br>

          <div class="card-deck">

              <div class="card">
                  <h5 class="card-header">Veterinaria</h5>
                  <div class="card-body">
                      
                      <div class="form-check col-md-2">
                          {{ form.vacunado }}
                          <label class="form-check-label" for="id_vacunado">Vacunado</label>
                      </div>

                      <div class="form-check col-md-2">
                          {{ form.desparasitado }}
                          <label class="form-check-label" for="id_desparasitado">Desparasitado</label>
                      </div>

                      <div class="form-check col-md-2">
                          {{ form.castrado }}
                          <label class="form-check-label" for="id_castrado">Castrado</label>
                      </div>
                      <br>
                      <label for="id_comentario">Comentario:</label>
                      {{ form.comentario }}
                  </div>
              </div>

              <div class="card">
                  <h5 class="card-header">Contacto</h5>
                  <div class="card-body">
                      <label for="id_telefono">Teléfono:</label>
                      {{ form.telefono }}
                      <br>
                      <label for="id_email">Email:</label>
                      {{ form.email }}
                  </div>
              </div>

          </div>

          <br>

          <div class="card-deck">

            <div class="card">
              <h5 class="card-header">Fotos</h5>
              <div class="card-body">
                  {{ form.foto1 }}
                  <br><br>
                  {% if animal.foto1 %}
                  <img src="{{animal.foto1.url}}" alt="animal.nombre" style="object-fit: cover; height: 300px;">
                  {% else %}
                  <img src="{% static 'adopcion/img/no-image.png' %}" alt="animal.nombre" style="object-fit: cover; height: 300px;">
                  {% endif %}
                  <hr>
                  {{ form.foto2 }}
                  {% if animal.foto1 and animal.foto2 %}
                  <br><br>
                  <img src="{{animal.foto2.url}}" alt="animal.nombre" style="object-fit: cover; height: 300px;">
                  {% endif %}
                  <br><br>
              </div>
            </div>

          </div>

          <br>

          <button name="submit" type="submit" class="btn btn-primary btn-block btn-lg">Actualizar</button>

        </form>

        <br/>

        <button type="submit" class="btn btn-danger btn-block" data-toggle="modal" data-target="#deleteConfirmationModal">Eliminar</button>
     
    </div>
    
    <br><br>
    <a href="{% url 'adopcion' %}">&larr; Volver</a>

        <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">Eliminar animal</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  ¿Estás seguro/a de que querés eliminar a "{{ animal }}" de la página?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                  <form method="POST" action="{% url 'eliminar-animal' animal.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                  </form>
                </div>
              </div>
            </div>
          </div>

    <script type="text/javascript">
      var specialKeys = new Array();
      specialKeys.push(8); //Backspace
      function IsNumeric(e) {
          var keyCode = e.which ? e.which : e.keyCode
          var ret = ((keyCode >= 48 && keyCode <= 57) || specialKeys.indexOf(keyCode) != -1);
          return ret;
      }
      var edad = document.getElementById("id_edad");
      var tel = document.getElementById("id_telefono")
      edad.onkeypress = IsNumeric;
      tel.onkeypress = IsNumeric;

      $(document).ready(function() {

        $("#id_vacunado").addClass('form-check-input');
        $("#id_desparasitado").addClass('form-check-input');
        $("#id_castrado").addClass('form-check-input');

        var tipo_animal = $("#id_tipo_animal").val();
        if (tipo_animal == "Perro") {
            $("#gato").hide();
            $("#perro").show();
        }
        else if (tipo_animal == "Gato") {
            $("#gato").show();
            $("#perro").hide();
        }
        else {
            $("#gato").hide();
            $("#perro").hide();
        }

        
        $("#id_tipo_animal").change(function() {
            var val = $(this).val();
            if (val == "Perro") {
                $("#gato").hide();
                $("#perro").show();
            }
            else if (val == "Gato") {
                $("#gato").show();
                $("#perro").hide();
            }
            else {
                $("#gato").hide();
                $("#perro").hide();
            }
            });
        });
    </script>

    {% else %}

    <center>
        <p>Tenés que ser el dueño de esta publicación para poder editarla.</p>
    </center>

    {% endif %}

{% endblock contenido %}

proyecto/adopcion/templates/adopcion/adopcion_form.html
{% extends "core/base.html" %}


{% block title %} En adopcion {% endblock title %}

{% block image %} {% load static %} {% static 'core/img/adopcion-bg.jpg'%} {% endblock image %}

{% block cabecera %}
<h1> Adoptá</h1>
<p> Encontrá tu compañía ideal</p>
{% endblock cabecera %}

{% block contenido %}

<a href="{% url 'adopcion' %}">&larr; Volver</a>
<br><br>

    {% if request.user.is_authenticated %}

    <div class="col-12">

        <form action="{% url 'agregar-animal' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="card-deck">
                <div class="card">
                    <h5 class="card-header">Detalles</h5>
                    <div class="card-body">
                        <label for="id_nombre">Nombre:</label>
                        {{ form.nombre }}
                        <br>
                        <label for="id_tipo_animal">Tipo de animal:</label>
                        {{ form.tipo_animal }}
                        <br>
                        <div id="perro">
                            <label for="id_raza_perro">Raza:</label>
                            {{ form.raza_perro }}
                            <br>
                        </div>
                        <div id="gato">
                            <label for="id_raza_gato">Raza:</label>
                            {{ form.raza_gato }}
                            <br>
                        </div>
                        <label for="id_sexo">Sexo:</label>
                        {{ form.sexo }}
                        <br>
                        <label for="id_tamaño">Tamaño:</label>
                        {{ form.tamaño }}
                        <br>
                        <label for="id_edad">Edad:</label>
                        {{ form.edad }}
                        <br>
                        <label for="id_tiempo">Tiempo:</label>
                        {{ form.tiempo }}
                        <br>
                        <label for="id_caracter">Caracter:</label>
                        {{ form.caracter }}
                        <br>
                        <label for="id_descripcion">Descripción:</label>
                        {{ form.descripcion }}
                    </div>
                </div>

            </div>

            <br>

            <div class="card-deck">

                <div class="card">
                    <h5 class="card-header">Veterinaria</h5>
                    <div class="card-body">
                        
                        <div class="form-check col-md-2">
                            {{ form.vacunado }}
                            <label class="form-check-label" for="id_vacunado">Vacunado</label>
                        </div>

                        <div class="form-check col-md-2">
                            {{ form.desparasitado }}
                            <label class="form-check-label" for="id_desparasitado">Desparasitado</label>
                        </div>

                        <div class="form-check col-md-2">
                            {{ form.castrado }}
                            <label class="form-check-label" for="id_castrado">Castrado</label>
                        </div>

                        {{ form.comentario }}
                    </div>
                </div>

                <div class="card">
                    <h5 class="card-header">Contacto</h5>
                    <div class="card-body">
                        {{ form.telefono }}
                        {{ form.email }}
                    </div>
                </div>

            </div>

            <br>

            <div class="card-deck">

                <div class="card">
                  <h5 class="card-header">Fotos</h5>
                  <div class="card-body">
                      <br>
                      {{ form.foto1 }}
                      <hr>
                      {{ form.foto2 }}
                      <br><br>
                  </div>
                </div>
    
              </div>

            <br>
            <small id="bodyHelpBlock" class="form-text text-muted">Los campos que contienen (*) son obligatorios.</small>
            <br>
            <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#publishConfirmationModal">Publicar</button>

            <div class="modal fade" id="publishConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="publishConfirmationModalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Publicar animal</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Tu publicación será revisada por los supervisadores de la página y evaluarán si puede ser publicada. No serás notificado cuando tu publicación sea aceptada.
                        <br>
                        Antes de continuar, revisá si completaste todos los datos obligatorios.
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button name="submit" type="submit" class="btn btn-primary">Publicar</button>
                    </div>
                    </div>
                </div>
            </div>
            
        </form>

    </div>

<br><br>
<a href="{% url 'adopcion' %}">&larr; Volver</a>

    <script type="text/javascript">
        var specialKeys = new Array();
        specialKeys.push(8); //Backspace
        function IsNumeric(e) {
            var keyCode = e.which ? e.which : e.keyCode
            var ret = ((keyCode >= 48 && keyCode <= 57) || specialKeys.indexOf(keyCode) != -1);
            return ret;
        }
        var edad = document.getElementById("id_edad");
        var tel = document.getElementById("id_telefono")
        edad.onkeypress = IsNumeric;
        tel.onkeypress = IsNumeric;

        $(document).ready(function() {

            $("#id_vacunado").addClass('form-check-input');
            $("#id_desparasitado").addClass('form-check-input');
            $("#id_castrado").addClass('form-check-input');

            $("#gato").hide();
            $("#id_tipo_animal").change(function() {
                var val = $(this).val();
                if (val == "Perro") {
                    $("#gato").hide();
                    $("#perro").show();
                }
                else if (val == "Gato") {
                    $("#gato").show();
                    $("#perro").hide();
                }
                else {
                    $("#gato").hide();
                    $("#perro").hide();
                }
            });
        });

    </script>

    {% else %}

    <center>
        <p><a href="{% url 'iniciar-sesion' %}">Iniciá sesión</a> para poder publicar animales.</p>
    </center>

    {% endif %}

{% endblock contenido %}